import Head from "next/head";
import { FromTheTopAnimation, ZoomInAnimation } from "../common/animations";
import { PopularShowList, ShowCard } from "../module/show/components";
import calculateDelay from "../common/utils/calculateAnimationDelay";
import { FunctionComponent } from "react";
import { useAppSelector } from "../common/hooks/store";
import ShowProvider, { useShow } from "../common/hooks/useShow";
import { Grid } from "../common/components/grid";
import { SeasonList } from "../module/season/components";
import { Nav } from "../common/components/nav";

const Intro: FunctionComponent = () => {
  const selectedShows = useAppSelector((state) => state.shows.selectedShows);
  const numberLeft = selectedShows ? 5 - selectedShows?.length : 5;

  return (
    <FromTheTopAnimation>
      <div className="flex flex-col gap-6 p-5">
        <h3 className="text-white text-3xl">
          Hey, select{" "}
          <strong
            className="text-transparent bg-clip-text"
            style={{
              backgroundImage:
                "linear-gradient(135deg, #CB5EEE 0%, #4BE1EC 100%)",
            }}
          >
            {numberLeft}
          </strong>{" "}
          of your favorite TV shows.
        </h3>
        <PopularShowList />
      </div>
    </FromTheTopAnimation>
  );
};

const ShowScreen: FunctionComponent = () => {
  const selectedShows = useAppSelector((state) => state.shows.selectedShows);

  return (
    <Grid>
      {selectedShows?.map((show, index) => (
        <ZoomInAnimation delay={calculateDelay(index)} key={index}>
          <ShowCard
            image={show.image}
            title={show.title}
            id={show.id}
            type="application"
          />
        </ZoomInAnimation>
      ))}
    </Grid>
  );
};

const SeasonScreen: FunctionComponent = () => {
  return <SeasonList />;
};

const EpisodesScreen: FunctionComponent = () => {
  return <div></div>;
};

const EpisodeScreen: FunctionComponent = () => {
  return <div></div>;
};

const Application: FunctionComponent = () => {
  const { selectedScreen } = useShow();

  return (
    <div>
      <Nav />
      {selectedScreen === "shows" && <ShowScreen />}
      {selectedScreen === "seasons" && <SeasonScreen />}
      {selectedScreen === "episodes" && <EpisodesScreen />}
      {selectedScreen === "episode" && <EpisodeScreen />}
    </div>
  );
};

export default function Home() {
  const selectedShows = useAppSelector((state) => state.shows.selectedShows);
  return (
    <>
      <Head>
        <title>Tv Shows Informations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShowProvider>
        <main className="bg-black min-h-screen">
          <div className="max-w-[1660px] m-auto">
            {selectedShows?.length === 5 ? <Application /> : <Intro />}
          </div>
        </main>
      </ShowProvider>
    </>
  );
}
