import Head from "next/head";
import { FunctionComponent } from "react";
import { useAppSelector } from "../common/hooks/store";
import ShowProvider, { useShow } from "../common/hooks/useShow";
import { Nav } from "../common/components/nav";
import { SelectedShowScreen, SelectShowScreen } from "../module/show/screens";
import { SeasonScreen } from "../module/seasons/screens";
import { EpisodeDataScreen, EpisodesScreen } from "../module/episode/screens";

const Application: FunctionComponent = () => {
  const { selectedScreen } = useShow();

  return (
    <div>
      <Nav />
      {selectedScreen === "shows" && <SelectedShowScreen />}
      {selectedScreen === "seasons" && <SeasonScreen />}
      {selectedScreen === "episodes" && <EpisodesScreen />}
      {selectedScreen === "episode" && <EpisodeDataScreen />}
    </div>
  );
};

export default function Home() {
  const selectedShows = useAppSelector((state) => state.shows.selectedShows);
  return (
    <>
      <Head>
        <title>Tv Shows Informations</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShowProvider>
        <main className="bg-black min-h-screen">
          <div className="max-w-[1660px] m-auto">
            {selectedShows?.length === 5 ? (
              <Application />
            ) : (
              <SelectShowScreen />
            )}
          </div>
        </main>
      </ShowProvider>
    </>
  );
}
